#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/ramboz/hlx-test-markupconfig.git"

strains:
  - name: default
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
